name: fintech

services:

    backend:
        build:
            context: ..
            dockerfile: _docker/Dockerfile.dev
            target: backend
        env_file:
            - ../.env
        volumes:
            - ../:/app
        ports:
            - 8005:8000
        networks:
            - fintech
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    celery-worker:
        build:
            context: ..
            dockerfile: _docker/Dockerfile.dev
            target: backend
        entrypoint: []
        command: uv run celery -A core worker -l info
        env_file:
            - ../.env
        volumes:
            - ../:/app
        networks:
            - fintech
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    redis:
        image: redis:7-alpine
        networks:
            - fintech
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped

    postgres:
        image: postgres:17-alpine
        env_file:
            - ../.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "7005:5432"
        networks:
            - fintech
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped

networks:
    fintech:

volumes:
    postgres_data:
