FROM python:3.13-slim AS backend

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TZ=America/Sao_Paulo \
    DJANGO_SETTINGS_MODULE=core.settings.dev \
    UV_PROJECT_ENVIRONMENT=/usr/local

RUN apt update && apt install -y --no-install-recommends \
    curl tzdata git bash build-essential ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1000 appuser \
    && useradd -u 1000 -g appuser -m -s /bin/bash appuser

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock /app/
RUN uv sync --frozen

COPY . /app/

COPY _docker/entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
